apiVersion: apps/v1
kind: Deployment
metadata:
  name: openswap-backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/backend:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: INFURA_API_KEY
          valueFrom:
            secretKeyRef:
              name: openswap-backend-secret
              key: infura-key
